src/app/modules/angular-slickgrid/models/editCommand.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts
editCommandHandler works in base slickgrid (6pac/SlickGrid) but was lost in Angular-Slickgrid. Very usefull option I think.
=> extend GridOption with editCommandHandler option

src/app/examples/grid-editor.component.html, src/app/examples/grid-editor.component.ts, src/app/examples/grid-headermenu.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/controlAndPlugin.service.ts, src/app/modules/angular-slickgrid/services/export.service.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts, src/app/modules/angular-slickgrid/services/gridEvent.service.ts, src/app/modules/angular-slickgrid/services/gridExtra.service.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts, src/app/modules/angular-slickgrid/services/resizer.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
Remove all `gridOptions` and `columnDefinitions` references from all Services. 
The reasons of doing so
- we have access to the Grid Options and Column Definitions from the Grid object
- simplify all `init` and creation of Services
- we can be more dynamic, user can change some Grid Options dynamically and they will be available in all Services since we are getting them from the Grid object when the time comes, so if options changed, we will see the latest.
Related to issue #20
=> refactor(services): remove gridOptions and columnDefinitions references

src/app/examples/grid-editor.component.ts, src/app/examples/grid-menu.component.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/multipleSelectOption.interface.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-bootstrap.scss, src/assets/lib/multiple-select/multiple-select.js
- add few new flags directly in `multiple-select.js` and remove previous code (that was not always working) new flags are:
- `autoAdjustDropHeight`
- `autoAdjustDropPosition`
- `autoAdjustDropWidthByTextSize`
- also in `multiple-select.js` you might want to use certain minimum or maximum height/width, so we also added the following options:
- `minWidth` (defaults to null, to use when `autoAdjustDropWidthByTextSize` is enabled)
- `maxWidth` (defaults to 500, to use when `autoAdjustDropWidthByTextSize` is enabled)
- `adjustHeightPadding` (defaults to 10, to use when `autoAdjustDropHeight` is enabled)
- `maxHeight` (defaults to 275, to use when `autoAdjustDropHeight` is enabled)
- removed duplicate code in Select Filters & Editors to toggling drop position (top/bottom) and replace it all by …
=> feat(multiselect): auto-adjust height, width & position of multiple-select.js

src/app/examples/grid-clientside.component.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/collectionOption.interface.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts, src/app/modules/angular-slickgrid/models/columnFilter.interface.ts, src/app/modules/angular-slickgrid/models/filterMultiplePassType.enum.ts, src/app/modules/angular-slickgrid/models/filterMultiplePassTypeString.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/services/collection.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, src/app/modules/angular-slickgrid/services/utilities.ts
- this allows to pass an array or a simple object to both `collectionFilterBy` and `collectionSortBy`
Tested with the following column definition
```typescript
{ 
id: 'duration', name: 'Duration (days)', field: 'duration', sortable: true, 
filterable: true,
filter: {
collectionAsync: this.http.get<{ option: string; value: string; }[]>(URL_SAMPLE_COLLECTION_DATA),
// you can pass single/multiple filterBy option(s)
collectionFilterBy: [{
property: 'value',
operator: OperatorType.notEqual,
value: 365
}, {
property: 'value',
operator: OperatorType.notEqual,
value: 360
}],
// when using multiple filters, it will by default chain the results after each pass
// this mean that each pass affect all the next passes (less and less results after each passes)
// but you have the option to change that …
```
=> feat(collection): support multiple filterBy/sortBy in CollectionService

src/app/examples/grid-editor.component.html, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts
The auto commit flag will attempt to commit the current editor when the
editor is focused out. However, not all editors behave the same so extra
logic had to be included in some editors. This means that the grid may not
be able to auto commit custom editors and it will be the
responsibility of the user building the editor.
**checkboxEditor**: Can be handled by the focusout event, but a click event
was added in the editor to make it behave more like a checkbox
**dateEditor**, **sliderEditor**: Prevent focus to the next editor
**longTextEditor**: Add focusout event to textarea, grid does not capture event
**selectEditor**: No focusout event so commit on close
**others**: handled by aurelia-slickgrid subscription to focusout
=> feat(editor): Add auto commit edit flag to grid options

src/app/examples/grid-clientside.component.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/collectionCustomStructure.interface.ts, src/app/modules/angular-slickgrid/models/multipleSelectOption.interface.ts, src/assets/lib/multiple-select/multiple-select.js
- in some cases the selected text (option text) might be too wide to show as selected text, this PR adds possibility to use a different property with shorter text
```typescript
{ 
id: 'duration', name: 'Duration (days)', field: 'duration', 
filter: {
collectionAsync: this.http.get<{ option: string; value: string; }[]>(URL_SAMPLE_COLLECTION_DATA),
customStructure: {
value: 'value',
label: 'label',
optionLabel: 'value', // if selected text is too long, we can use option labels instead
labelSuffix: 'text',
},
model: Filters.multipleSelect,
// we could add certain option(s) to the "multiple-select" plugin
filterOptions: {
// if we want to display shorter text as the selected text (on the select filter itself, parent element)
useSelectOptionLabel: true // or "useSelectOptionLabelToHtml" the …
```
=> feat(select):  add option to use label as selected text

package.json, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/examples/grid-frozen.component.html, src/app/examples/grid-frozen.component.scss, src/app/examples/grid-frozen.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-bootstrap.scss, src/app/modules/angular-slickgrid/styles/slick-grid.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss, src/app/modules/angular-slickgrid/styles/slickgrid-examples.scss, src/main.ts, tsconfig.json
=> feat(frozen): add Frozen/Pinned rows/columns Feature

src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/filter.interface.ts, src/app/modules/angular-slickgrid/services/filter.service.ts
- add code in place to know if the Filter was rendered more than 1x time (happens when using backendServiceApi)
=> fix(filter): Select Filter "addBlankEntry" sometimes add 2x entries

src/app/modules/angular-slickgrid/models/formatter.interface.ts
Hi slickgrid expects the formatter to be able to send an object or a string, if it is an object then you can specify a style as well as content.
=> Formatter returns a string or an object

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.ts, src/app/modules/angular-slickgrid/services/backend-utilities.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/index.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- the refactoring is mostly because of Spinner with Http Interceptor not always stopping, it might not be related at all but perhaps keeping Observable as Observable (instead of casting them to Promise) might help with this spinner issue.
- also the refactoring moves all the backend service processes into 1 method which deals with all of these processes. So instead of troubleshooting in multiple area, it will all be in the same method (DRY)
- also worth to know that the Backend Service API still support Promise, we won't remove that feature, so both Promise & Observable are supported and we won't cast any of them anymore
=> refactor(backend): remove all castToPromise and keep Observables as is

src/app/modules/angular-slickgrid/extensions/checkboxSelectorExtension.ts, src/app/modules/angular-slickgrid/extensions/columnPickerExtension.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/headerButtonExtension.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/rowMoveManagerExtension.ts, src/app/modules/angular-slickgrid/formatters/progressBarFormatter.ts, src/app/modules/angular-slickgrid/models/gridMenu.interface.ts, src/app/modules/angular-slickgrid/models/headerButton.interface.ts, src/app/modules/angular-slickgrid/models/headerMenu.interface.ts, src/app/modules/angular-slickgrid/models/rowMoveManager.interface.ts
- this event is only useful for the events that have more options & commands like HeaderMenu, HeaderButtonMenu, ... so we add this event only to these extensions
=> feat(event): add onExtensionRegistered to a few extensions

src/app/examples/custom-angularComponentEditor.ts, src/app/examples/custom-inputEditor.ts, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/constants.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts
- these 2 new options might not be supported by all Editors (e.g. checkbox doesn't use ENTER key)
- the "alwaysSaveOnEnterKey" can be helpful if user want to save value regardless if it's null or not
- also fixed integer editor validation, a few validations were missing like minValue/maxValue/...
=> feat(editors): add "required" and "alwaysSaveOnEnterKey" options

src/app/examples/custom-inputEditor.ts, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts, src/app/modules/angular-slickgrid/filters/autoCompleteFilter.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/collectionCustomStructure.interface.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, tsconfig.json
- as soon as the column definition property "field" includes a dot "." we consider it as a complex object and the lib deals with a complex object differently. On each Editor, we have to return the object but if the "field" contains the "." then we need to pull the object name before the dot. For example, if our "field" is "user.firstName" then our complex object is "user" and we should return in most cases the "user" object
=> fix(editor): allow all Editors to work with complex objects

src/app/examples/custom-angularComponentFilter.ts, src/app/examples/custom-inputFilter.ts, src/app/examples/grid-graphql.component.html, src/app/examples/grid-graphql.component.ts, src/app/modules/angular-slickgrid/filters/autoCompleteFilter.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundSliderFilter.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/filters/inputMaskFilter.ts, src/app/modules/angular-slickgrid/filters/nativeSelectFilter.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/filters/sliderFilter.ts, src/app/modules/angular-slickgrid/models/filter.interface.ts, src/app/modules/angular-slickgrid/models/filterCallback.interface.ts, src/app/modules/angular-slickgrid/services/filter.service.ts
- adding shouldTriggerQuery to know when to call a query or not. This fixes the multiple queries sent by calling 1 clearFiltersAndSorts
=> fix(backend): add Filter shouldTriggerQuery

.vscode/launch.json, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/formatters/checkmarkFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/checkmarkFormatter.ts, src/app/modules/angular-slickgrid/models/editor.interface.ts, src/app/modules/angular-slickgrid/services/gridEvent.service.ts, src/app/modules/angular-slickgrid/services/utilities.ts, src/assets/lib/multiple-select/multiple-select.js
- multiple issues found while using `enableExcelCopyBuffer: true` and copy pasting cell values back in the grid
1. pasting was creating additional dom elements
2. cell was not active (not in focus) and paste was behaving incorrectly because of that
3. few Editors paste were not working correctly either
=> fix(copy): copy+paste cells was not working, closes #164

src/app/examples/custom-inputEditor.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts
- the Editors all have their own "validate()" method that verifies if the value is valid or not and we should also verify the values when pasting into the grid
=> fix(editors): not allow grid paste of invalid values, issue #171

src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts
=> force user input in autocomplete

src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts
Hi there,
Just noticed that I missed something on this feature. It is a small change but it detects if the user has used the `minLength` and applies it to the field. For example if you want the user to be able to clear the input or be able to add a text with less than 3 characters.
=> added option for user to select the length of autocomplete

src/app/modules/angular-slickgrid/filter-conditions/dateEuroFilterCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/dateEuroShortFilterCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/executeMappedCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/index.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeEuroAmPmFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeShortEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/dateEuroFormatter.ts, src/app/modules/angular-slickgrid/formatters/dateTimeEuroAmPmFormatter.ts, src/app/modules/angular-slickgrid/formatters/dateTimeEuroFormatter.ts, src/app/modules/angular-slickgrid/formatters/dateTimeShortEuroFormatter.ts, src/app/modules/angular-slickgrid/formatters/index.ts, src/app/modules/angular-slickgrid/models/fieldType.enum.ts, src/app/modules/angular-slickgrid/services/utilities.ts, src/app/modules/angular-slickgrid/sorters/__tests__/dateEuroShortSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/__tests__/dateEuroSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/dateEuroShortSorter.ts, src/app/modules/angular-slickgrid/sorters/dateEuroSorter.ts, src/app/modules/angular-slickgrid/sorters/index.ts, src/app/modules/angular-slickgrid/sorters/sorterUtilities.ts
=> feat(euro): add Euro Formatters and Sorters (day/month/year)

package.json, src/app/examples/grid-rowdetail.component.html, src/app/examples/grid-rowdetail.component.ts
- prior to this version, a scrolling always appeared in the row detail panel
- closes #180
=> fix(rowDetail): update to latest SlickGrid version, fixes #180

src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/extensions/checkboxSelectorExtension.ts, src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts, src/app/modules/angular-slickgrid/models/column.interface.ts
- excludeFromColumnPicker for the Column Picker
- excludeFromGridMenu for the Grid Menu
=> feat(menu): add options to exclude column titles from Menus, closes #189

src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts
- when user focused on an empty field that had integer editor and then user was focusing away it was showing the field as an invalid integer. In reality when there is no field change, we don't need to validate at all
=> fix(editor): integer editor was always showing invalid when null value

src/app/examples/grid-editor.component.html, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- Column with Editors are special because we need to swap them internally in the library to a property named "internalColumnEditor", we do this because SlickGrid has "editor" reserved to a factory but that is completely different than the implementation in Angular-Slickgrid, so if user add a column dynamically, it should also be analyzed as well at that time.
=> fix(editor): dynamically adding editor column throws error, fixes #195

src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/models/filterChangedArgs.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- both "queryFieldFilter" and "queryFieldSorter" should have precedence over "queryField", then "field". For example (1- "queryFieldFilter", if not found then 2- "queryField", if not found then "field"
=> fix(queryField): queryFieldFilter and queryFieldSorter have precedence

src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/extension.service.ts
- after adding/modifying the column definitions, the change(s) of new column header, should also be reflected in both Column Picker & Grid Menu
- fixes #233
=> fix(menu): Column Picker & Grid Menu not updated dynamically, fixes #233

.vscode/tasks.json, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/tsconfig.spec.json, test/cypress/integration/example1.spec.js, test/cypress/integration/example6.spec.js, test/cypress/integration/home.spec.js
- when trying to clear a filter that was empty, there is no reason to trigger a filter change
- to replicate the issue, you could go to the OData or GraphQL example and hover over a column with an empty filter, then choose "Clear Filter" from the header menu. The spinner should stop
=> fix(backend): clear empty filter by header menu not stopping spinner

src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts
=> fix(gridMenu): adding user customItems in GridMenu longer showing, fix #244

src/app/examples/grid-rowselection.component.html, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/extension.service.ts, test/cypress/integration/example10.spec.js
- this was a regression bug, cannot pinpoint exactly since when this regression bug started
- the isssue, row selection and filtering are completely independent, they don't talk to each other and the filtering as no clue which row it was selected prior to the filter, so the best we can do is to remove any row selection after typing a search filter (filtering)
- update Jest unit tests & add Cypress E2E tests to cover this in the UI as well
=> fix(selection): selected row should be none after filtering, closes #249

src/app/examples/grid-odata.component.html, src/app/examples/grid-odata.component.ts, src/app/modules/angular-slickgrid/models/odataOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts, test/cypress/integration/example5.spec.js
- defaults to OData version 2 (which uses substringof)
- fixes issue #263 
- Tasks
`$top=20&$orderby=Name asc&$filter=(Gender eq 'male' and substringof('John', Name))`
`$top=20&$orderby=Name asc&$filter=(contains(Name, 'John') and Gender eq 'male')`
=> fix(odata): use contains with OData version 4, fixes #263

src/app/modules/angular-slickgrid/styles/slick-default-theme.scss, src/app/modules/angular-slickgrid/styles/slick-grid.scss
- found a commit in SlickGrid to address Firefox styling issue https://github.com/6pac/SlickGrid/commit/a8d4452b625270b7671eb0e2a0d84aa6cc556656
=> fix(styling): styling issue in Firefox after col reordering, fixes #297

src/app/app.module.ts, src/app/examples/custom-actionFormatter.component.ts, src/app/examples/grid-angular.component.html, src/app/examples/grid-angular.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/models/exportOption.interface.ts, src/app/modules/angular-slickgrid/models/graphqlResult.interface.ts, src/app/modules/angular-slickgrid/models/graphqlServiceOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/export.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/export.service.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts
- a new flag "addListSeparator" was added to the GraphQL Backend Service, this flag when set will ask the GraphQL on the backend side to return the current user list separator (in English it's a comma but in French it's a semicolon). For example, with .Net Core, we can get this list separator by the `CultureInfo.TextInfo.ListSeparator`
=> feat(export): add delimiter/listSeparator override to use with GraphQL

src/app/modules/angular-slickgrid/editors/__tests__/dateEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/sliderEditor.spec.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts
- certain Editors were triggering a save when clicking/opening the Editor when autocommit was enabled even though the value if the field was the same since we just opened the editor.
=> fix(editor): autocommit should not save if value is the same as before

src/app/modules/angular-slickgrid/services/__tests__/excelExport.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/export.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts, src/app/modules/angular-slickgrid/services/export.service.ts
- this happen when user try to use the export method without enabling the service in the grid option
=> refactor(export): should throw error when grid/dataview objects are null

src/app/examples/grid-angular.component.ts, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts, test/cypress/integration/example9.spec.js
- deprecate `elementOptions` and push to use `editorOptions` instead
=> fix(editor): use editorOptions only

src/app/modules/angular-slickgrid/components/__tests__/slick-pagination-without-translate.component.spec.ts, src/app/modules/angular-slickgrid/components/__tests__/slick-pagination.component.spec.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.html, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/formatters/checkmarkFormatter.ts, src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss, test/cypress/integration/example5.spec.js
- if we filter the data and an empty dataset is returned, we should display "Page 1 of 1", not "Page 0 of 0". Also instead of "0-0 of 0 items", we should hide the "0-0" and only display "0 items". This matches roughly what UI-Grid does (in their case, they actually even hide the total count).
- this fixes some small issues that I have seen, sometime the page 0 of 0 was sticking even though we removed the filter, so it's better to use Page 1 of 1 as a minimum
- update Cypress E2E test
**BEFORE**
**AFTER**
=> fix(pagination): never display page 0, minimum should be page 1

README.md, src/app/examples/grid-clientside.component.html, src/app/examples/grid-clientside.component.ts, src/app/examples/grid-draggrouping.component.html, src/app/examples/grid-draggrouping.component.ts, src/app/examples/grid-graphql.component.html, src/app/examples/grid-graphql.component.ts, src/app/examples/grid-odata.component.html, src/app/examples/grid-odata.component.ts, src/app/examples/grid-range.component.html, src/app/examples/grid-range.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/__tests__/bsDropdown.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/bsDropdown.service.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, test/cypress/integration/example25.spec.js, test/cypress/integration/example4.spec.js, test/cypress/integration/example5.spec.js, test/cypress/integration/example6.spec.js
- prior to this change, we could update Sorting (sorters) only through "presets" the caviat was that it was only on first page load. Now with this new change we will be to update Sorting on the fly at any time.
=> feat(sorting): provide method to apply grid sorting dynamically

src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- allow to bypass changed events when calling updateFilters / updateSorting
- also allow to bypass calling the backend query (
- useful when calling both updates in sequence and we want only 1 query sent
=> feat(events): allow to bypass changed events when calling updateFilters/Sorting

src/app/modules/angular-slickgrid/filters/__tests__/compoundDateFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/dateRangeFilter.spec.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/dateRangeFilter.ts, src/app/modules/angular-slickgrid/formatters/__tests__/decimalFormatter.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- fixes #346
- when using a locale that Flatpickr doesn't support, like "ua", it should use "en" (English) as default locale.
- it will display a console warning that this locale is not supported but not throw an error (unless user set a different locale, see next)
- user can choose to override the locale by setting locale to use via 
- `filter: { filterOptions: { locale: 'en' } }`
New behavior with this PR, it will now show a console warning to advise user that the locale is not supported, it will use English locale instead of throwing an error
=> fix(filter): Date Filters using Flatpickr throw error w/invalid locale

src/app/examples/grid-graphql.component.ts, src/app/examples/grid-localization.component.html, src/app/examples/grid-localization.component.ts, src/app/examples/grid-state.component.html, src/app/modules/angular-slickgrid/filter-conditions/numberFilterCondition.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputMaskFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/selectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, test/cypress/integration/example1.spec.js, test/cypress/integration/example10.spec.js, test/cypress/integration/example12.spec.js, test/cypress/integration/example16.spec.js, test/cypress/integration/example5.spec.js, test/cypress/integration/example6.spec.js, test/cypress/integration/example9.spec.js, test/cypress/integration/home.spec.js
- when adding the new Update Filter Dynamically feature, I accidently switch the default input text filter operator to EQ (equal) though it should be set to empty string so that it can search substring anywhere in the string.
- added Cypress E2E tests to cover this
fixes #349
=> fix(filter): default operator of input filter should be empty

package.json, src/app/examples/grid-menu.component.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-controls.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss, test/cypress/integration/example9.spec.js
- styling issue was with item/command being disabled, their parent css were not changing to grey but they should. For example, if we disable a Grid Menu command, then it's text content and icon should turn grey regardless of any parent css classes (cssClass, textCssClass)
=> fix(styling): use latest SlickGrid version and fix some styling issues

src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/backend-utilities.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- when user calls multiple requests, that could happen after typing new input search term in a filter before the previous query is finished and/or calls the (Enter) key multiple times after typing his search term. Calling and queueing multiple queries might re-render the grid unnecessarily with different dataset and produces a flashing effect to the eyes.
- it could also, in some cases, display incorrect data when for example we have 2 queries called in sequence (to filter some data) and the (query 2) resolves before (query 1, because that one was slower), which means they resolved in an inverse sequence, that in terms will end up displaying the wrong final dataset
=> fix(backend): cancel prior http calls to avoid inconsistent data shown

package.json, src/app/modules/angular-slickgrid/services/excelExport.service.ts
- create an external excel-builder-webpacker which is derived from the excel-builder-webpack with the main difference that all npm packages are up to date
- ref #377
=> fix(build): create & use separate excel-builder package to fix security

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/models/currentPagination.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/backend-utilities.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, test/cypress/integration/example05.spec.js, test/cypress/integration/example10.spec.js
- calling Clear Sorting from the Grid Menu was triggering 2x Grid State changes while it should be only 1 event
- Pagination was wrong after typing a filter returning 0 items and then removing the filter, the from-to was off
- also remove pageSizes from Grid State, it's not that useful there
=> fix(state): Clear Sort should trigger only 1 event & fix Pagination

src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts
- when using local grid, the DataView should be reset to page 0
=> fix(pagination): on filter change pagination should reset to 1st page

src/app/examples/grid-contextmenu.component.ts, src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/models/excelExportOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/excelExport.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts
code referenced from another fork in this particular [commit](https://github.com/drinac/Angular-Slickgrid/commit/275e099c8a55f0eb43935249dbf71e0c02066afe) 
- add the following `excelExportOptions`
- `customColumnWidth` 
- `columnHeaderStyle`
- add the following Column options
- `exportColumnWidth`
- `exportCustomGroupTotalsFormatter`
=> feat(excel): add some extra styling & width options for Excel export

src/app/examples/grid-editor.component.ts, src/app/examples/grid-localization.component.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- when user has Editors and Row Selection, user must rebuild the facade (internalColumnEditor into editor)
=> fix(columns): remove columns dynamically with Editors, fixes #406

src/app/modules/angular-slickgrid/services/__tests__/utilities.spec.ts, src/app/modules/angular-slickgrid/services/utilities.ts
- when using both together, 1 was cancelling the other. To fix this, I rewrote the code use text split by the decimal and then recombining them as a new text with necessary thousand & decimal separators
with updated code, the result is now as shown below
1. first column has `thousandSeparator: '.'` and `decimalSeparator: ','`
2. second column has `thousandSeparator: ','` and `decimalSeparator: '.'`
=> fix(formatters): decimalSeparator & thousandSeparator work tgt, fix #411

src/app/modules/angular-slickgrid/filter-conditions/__tests__/stringFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/stringFilterCondition.ts
- when using OperatorType.empty or OperatorType.contains, they should do a comparison of passing when item contains the substring of search term
=> fix(filter): string filter should also work when using Contains

src/app/examples/grid-rowmove.component.html, src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/rowMoveManagerExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/rowMoveManagerExtension.ts, src/app/modules/angular-slickgrid/models/rowMoveManager.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts, src/app/modules/angular-slickgrid/services/extension.service.ts, test/cypress/integration/example17.spec.js, test/cypress/package.json
- now create column definition just by the enableRowMoveManager flag
- also keep row selection with dataview syncGridSelection
- latest slickgrid version also brought the usabilityOverride callback method that was added in RowMoveManager plugin
- possible ref #256
=> feat(extension): add latest slickgrid with RowMove improvements

src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/sorters/__tests__/dateIsoSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/__tests__/numericSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/__tests__/sorterUtilities.spec.ts, src/app/modules/angular-slickgrid/sorters/__tests__/stringSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/dateUtilities.ts, src/app/modules/angular-slickgrid/sorters/numericSorter.ts, src/app/modules/angular-slickgrid/sorters/sorterUtilities.ts, src/app/modules/angular-slickgrid/sorters/stringSorter.ts
- this is an opt-in flag because it could bring unwanted behavior and for example it breaks the Row Detail UI when sorting undefined values, so user can opt-in but it's off by default
=> feat(sort): add valueCouldBeUndefined column flag to help sorting

src/app/examples/grid-grouping.component.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts
- just by changing the operator from a compound filter shouldn't do any search yet and shouldn't result to an empty grid, we should only start searching when there's a real value entered
=> fix(filter): when entering filter operator it shouldn't do any filtering

src/app/app.component.scss, src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, test/cypress/package.json
in certain occasion we don't know at hand which field name to use, we might just know depending on certain logic (e.g. if item dataContext has a product type "I" then use field "catalogNumber" but if it's type "P" use field "productCategoryNumber", ...)
=> feat(query): add queryFieldNameGetterFn callback know which field to use

src/app/examples/grid-headermenu.component.scss, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-bootstrap.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss
- we now show a hint while hovering the column. It helps identify if the hovering column is sortable or not, if user doesn't want this behavior he can simply change the SASS variable to opacity of 0.
=> feat(style): add Sort icon hint on hover when column is sortable

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/shared.service.spec.ts, src/app/modules/angular-slickgrid/services/shared.service.ts
- fixes #438
- this command "Toggle Filter Row" disappeared if it happens to have the filter row hidden when calling translate. This PR fixes it but while fixing this, it was also found that the Filter row MUST be visible BEFORE calling the translation service else the filters don't get recreated and that is even worst.
The Filters MUST be shown BEFORE calling the translation (the lib will do show the header row by itself internally to counter this issue). If we aren't showing the Filters prior to a language change, this is what happens, filters aren't re-created
So the fix is to show the Filter row anytime the translation service is called (when switch language) as shown below. We show the header row then we translate
=> fix(gridMenu): command "Togge Filter" disappeared, fixes #438

package.json, src/app/modules/angular-slickgrid/global-grid-options.ts
- fixes #440
- there was a small issue in core lib when using "datasetIdPropertyName" other than "id" so update to latest SlickGrid version which has the fix
- change default grid options of Row Detail "useRowClick" property to false
=> fix(rowDetail): use latest SlickGrid to fix issue with id, fixes #440

src/app/modules/angular-slickgrid/services/export-utilities.ts
- in some cases the user might have a formatter without any value or a "field" that is not in the dataContext, this however shouldn't block the use of exportWithFormatter
=> fix(formatter): exportWithFormatter should work with undefined item prop

src/app/modules/angular-slickgrid/models/fileType.enum.ts
- PDF and DOC are unsupported file type since there are no Exporter Services that exist for them, so they should be removed from acceptable file type formats
- closes #452
=> fix(export): remove unsupported file type, closes #452

package.json, src/app/examples/grid-menu.component.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridMenu.interface.ts, test/cypress/integration/example01.spec.js, test/jest.config.js
- add "headerColumnValueExtractor" callback in the global grid options to deal with grouped header titles
- also add 2 other new options "contentMinWidth" and "useClickToRepositionMenu"
- this requires a new SlickGrid core version with these new options
- requires this core lib [PR](https://github.com/6pac/SlickGrid/pull/491) be merged and released under a new version
=> fix(gridMenu): column picker list should include grouped header titles

src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts
=> fix(locale): use correct locale text operator tooltip, closes #468

src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts
=> fix(odata): encode URI also for IN/NIN operators, fixes #463

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
=> fix(footer): custom footer metric texts could not be changed, fixes #470

src/app/modules/angular-slickgrid/styles/slick-plugins.scss
- not an issue with Bootstrap but other frameworks like Bulma had this issue which it was overriding the SlickGrid cell-menu/context-menu styling because of these menus use generic css dropdown/dropup classes
=> fix(styling): cell/context menus get re-position below the grid

src/app/modules/angular-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts
- after hiding/showing columns from ColumnPicker/GridMenu we need to re-create the header grouping titles
=> fix(header): re-create header grouping title after changing picker cols

src/app/modules/angular-slickgrid/services/excelExport.service.ts
=> fix(excel): Excel Export add mime type to work in Firefox, fixes #500

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general.md, .github/issue-close-app.yml, src/app/modules/angular-slickgrid/filters/selectFilter.ts
- when user is using only a single Locale, the Select Filter (single/multi) should use the Locale text instead of the translation text
=> fix(filter): Select Filter should use default locale without translation

src/app/modules/angular-slickgrid/components/slick-pagination.component.html, src/app/modules/angular-slickgrid/components/slick-pagination.component.ts
I found out that the Bootstrap styling applied to the DOM element does not block clicks from it, the reason is because they are in fact `href` links which cannot by disabled (according to w3c specs), so it's better to check if action is enabled before proceeding with clicks
=> fix(pagination): disabled page buttons should not be clickable

src/app/examples/grid-graphql.component.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundSliderFilter.ts, src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts
- grid presets should work with short/long operator names, basically StartsWith/EndsWith were not working correctly while a*/*z were working correctly, both options should work
=> fix(presets): compound filters operator not working correctly w/presets

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, test/cypress/integration/example05.spec.js
- when there is no more column to sort, we could resort by default sort id which would display dataset the way it was when it was first loaded
- ref SO question: https://stackoverflow.com/questions/62489108/angular-slickgrid-column-wise-remove-sort-option-not-working-properly
- also found that Clear Column Sort on a Local Grid was not trigger a "sortChanged" event while it should so that the Grid State is also notified
=> feat(sorting): header menu clear sort, reset sorting when nothing left

src/app/modules/angular-slickgrid/editorValidators/floatValidator.ts, src/app/modules/angular-slickgrid/editors/__tests__/floatEditor.spec.ts
- basically 0.3 and .3 should be both accepted, the second one wasn't and this PR fixes it
=> fix(editor): float validator should accept decimal even without 0 suffix

package.json, src/app/modules/angular-slickgrid/formatters/__tests__/dateIsoFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/formatterUtilities.ts, test/jest-global-setup.js, test/jest.config.js, test/setup-jest.ts
- e.g. when '2099-12-31T00:00:00.000Z' in my TZ (EST) the DateIso Formatter will transform this in 2099-12-30 instead of 2099-12-31 because it assumes that the TZ must be included
=> fix(formatter): add possibility to parse a date formatter as a UTC date

src/app/modules/angular-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/dualInputEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/floatEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/integerEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/longTextEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/textEditor.spec.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts
- we were already checking for null value but undefined is another possibility, so now it checks for null/undefined in isValueChanged() method
=> fix(editor): shouldn't call cell changed when cell value is undefined

src/app/examples/grid-rowselection.component.ts, src/app/examples/grid-tree-data-parent-child.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- the Tree Data must execute pre-filtering with Tree Data when having Grid Preset Filters
=> fix(filter): Grid Preset Filters should work with Tree Data View

src/app/examples/grid-additem.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- we should use DataView transactions as much as possible when dealing with multiple items (array) in 1 call, that is true for (addItems, deleteItems, updateItems)
- DataView `beginUpdate` ...  `endUpdate`
=> feat(core): use DataView transactions with multiple item changes

src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/__tests__/dateEditor.spec.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/models/column.interface.ts
- we now have 3 available types to use with the Date Editors formatting
1. `type` (data input format),
2. `outputType` (picker display format)
3. `saveOutputType` (save format)
=> fix(editors): add saveOutputType to finally have proper save format

src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-pagination.scss
- using SASS variable in `calc` should be interpolate with `#{}` like `calc(#{sass-var}-2px)`
- fixes new bug found from previous PR #529
=> fix(styling): sass variable should be interpolate before using calc

src/app/modules/angular-slickgrid/services/extension.service.ts
On line 293, instead of checking for ExtensionName.draggableGrouping, code is checking for ExtensionName.rowDetailView, due to which if the rowDetailVIew is on then draggableGrouping can't be on. This is causing the issue when we enable both.
=> fix(extensions): draggable grouping called wrong check, fixes #538

src/app/examples/grid-angular.component.ts, src/app/modules/angular-slickgrid/constants.ts, src/app/modules/angular-slickgrid/editorValidators/integerValidator.ts, src/app/modules/angular-slickgrid/editorValidators/textValidator.ts, src/app/modules/angular-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/longTextEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/textEditor.spec.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-editors.scss
- add a text length counter (currentTextLength/maxLength) to the LongText Editor
- the new `minLenght`, `maxLength` options can be used by the following Editors (autoComplete, longText, text)
- also flip the position of the Cancel/Save buttons, Cancel should be on the left and Save on the right
=> feat(editors): add min/max length options to text editors

src/app/modules/angular-slickgrid/extensions/__tests__/contextMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/contextMenuExtension.ts
- seems like it was working only when "enableTranslate" was active, it should now work in both cases with/without translations
=> fix(extensions): adding Context Menu custom commands was not working

src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts
- refresh of each row detail not happening correctly with "datasetIdPropName", this was due to the fact that the View is saved as a "CreatedView" interface and that is kept with "id" not with "datasetIdPropName"
- found out that I made a mistake when adding the `datasetIdPropName`, I keep the View with an `id` not with the dynamic `datasetIdPropName` and so I was keeping all the Views with `undefined` instead of their correct associated `id` (or custom `id`)... long story short, the refresh of each Row Detail wasn't working correctly with using a custom Id with `datasetIdPropName`
- fixes #546
=> fix(extensions): Row Detail not always refreshing w/customId, fixes #546

src/app/examples/grid-rowdetail.component.ts, src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts
- it seems that when trying to find the DOM element of the row detail, we should always use the last one instead of the first one found
- final fix for issue #546
=> fix(extension): Row Detail gets blanked out for no reason, fixes #546

src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts
- it was throwing an error when the item dataContext did not have the label (or custom label) property inside the item dataContext
=> fix(editors): AutoComplete Editor might have undefined object label

package.json
- there are a few new bugs created by the latest Flatpickr version, for now it's best to fix our version to `4.6.3` which is fully working
=> fix(core): latest Flatpickr breaks Date Filters/Editors

.circleci/config.yml, package.json, src/app/examples/grid-rowmove.component.html, src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/extensionUtility.spec.ts, src/app/modules/angular-slickgrid/extensions/extensionUtility.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/models/gridMenuItem.interface.ts, src/app/modules/angular-slickgrid/models/headerMenu.interface.ts, src/app/modules/angular-slickgrid/models/menuItem.interface.ts, src/app/modules/angular-slickgrid/models/slickEditorLock.interface.ts, src/app/modules/angular-slickgrid/models/slickGrid.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/utilities.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/grid.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, src/app/modules/angular-slickgrid/services/utilities.ts, src/app/modules/angular-slickgrid/styles/slick-controls.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss, test/cypress/integration/example17.spec.js
- The new methods are:
- `filterService.toggleFilterFunctionality()`
- `sortService.toggleSortFunctionality()`
- `gridService.hideColumnByIndex(columnIndex)`
- `gridService.hideColumn(column)`
=> feat(services): add Toggle Filtering/Sorting & Hide Column methods

src/app/modules/angular-slickgrid/editors/selectEditor.ts
- the problem was noticeable after opening/closing the select dropdown multiple times
=> fix(editors): add blank entry on Select Editor should happen once

src/app/modules/angular-slickgrid/filter-conditions/__tests__/dateIsoFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/executeMappedCondition.ts, test/tsconfig.spec.json
- if we pass a Date object that has time and we use a dateIso format, or any other without time, we should disregard the time portion when using the CompoundDate Filter
=> fix(filters): disregard time when filtering date only format

src/app/examples/grid-graphql.component.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts
- when using "addBlankEntry" or "addCustomFirstEntry", the SelectFilter was affecting SelectEditor (and vice versa) because the collection was used by ref, so to fix this we can just do a copy of the collection before dealing with it
=> fix(select): make a collection array copy to avoid change by ref

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, test/cypress/package.json
- a regression was observer when using GridState/GridPresets with Local Storage, whenever clearing a Filter, it would put back the preset filter.
=> fix(filters): tree data presets caused regression in any grid w/presets

src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss
- it seems that we need to fix a max width so that it won't go over in BS4
=> fix(styling): Compound Filter Operator dropdown too wide in BS4

src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-bootstrap.scss, src/app/modules/angular-slickgrid/styles/slick-grid.scss
- add frozen to both the pre-header & header columns
- add SASS variables to customize border on these 3 properties (pre-header, header, header-row aka filter row)
=> feat(styling): add frozen on all possible elements with SASS variables

package.json, src/app/examples/grid-colspan.component.ts, src/app/examples/grid-frozen.component.ts, src/app/examples/grid-graphql-nopage.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts
- the `alwaysShowVerticalScroll` flag should be dealt directly in the core and it should never show vertical scroll on left frozen container, even when the `alwaysShowVerticalScroll` is set to True (see core lib [PR #537](6pac/SlickGrid#537))
- requires core lib [PR #537](6pac/SlickGrid#537) to be merged and released
=> fix(core): don't override alwaysShowVerticalScroll flag

src/app/modules/angular-slickgrid/models/gridStateChange.interface.ts
Both the service and the tests use the CurrentColumn type
for the event GridStateType.column
=> fix(interfaces): column types in GridStateChange

.circleci/config.yml, angular.json, package.json, src/app/app-routing.module.ts, test/cypress/cypress.json, test/cypress/integration/example01.spec.js, test/cypress/integration/example07.spec.js, test/cypress/integration/example08.spec.js, test/cypress/integration/home.spec.js
- run a Prod build and then use http-server to serve Cypress E2E tests
=> refactor: use http-server instead of webpack to run Cypress E2E tests

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- when jQuery mousewheel is imported, SlickGrid attaches a scroll handler which prevent scrolling to work as normal, this however should only be used with frozen grids since it creates other issues like seen in Row Detail were it doesn't behave correctly
- NOTE that this is more of a patch and a SlickGrid grid option flag would be better to handle that, possibly create a flag in future SlickGrid version
- fixes #618
=> fix(extensions): import jQuery mousewheel only with frozen, fixes #618

src/app/modules/angular-slickgrid/formatters/__tests__/fakeHyperlinkFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/fakeHyperlinkFormatter.ts, src/app/modules/angular-slickgrid/formatters/index.ts
- Takes any text value and display it as a fake a hyperlink (only styled as an hyperlink)
=> feat(formatters): add a fake hyperlink formatter

src/app/examples/grid-odata.component.html, src/app/examples/grid-odata.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, test/cypress/integration/example05.spec.js
- add a new paginationOptions getter/setter to avoid incomplete gridOptions passed by the OData result callback, merging the gridOptions was incomplete because it was only merging with the local gridOptions instead of the local+global gridOptions
- basically we won't be able to see the Empty Dataset Warning with OData unless we modified the code and use the new setter. Keeping the old code will still work but just won't display the warning when dataset is empty
=> fix(backend): OData/GraphQL pagination should display warning on empty

src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/models/hideColumnOption.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- deprecated previous methods (hideColumn, hideColumnByIndex) since the new methods offer more values with extra options to resize and/or hide from pickers
=> feat(services): add 2x new methods hideColumnById or ..byIds

src/app/modules/angular-slickgrid/formatters/__tests__/alignRightFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/centerFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/treeFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/yesNoFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/alignRightFormatter.ts, src/app/modules/angular-slickgrid/formatters/boldFormatter.ts, src/app/modules/angular-slickgrid/formatters/centerFormatter.ts, src/app/modules/angular-slickgrid/formatters/index.ts
- center already existed but we can add `alignCenter` to be in line with the other `alignRight` Formatter
- note also that there's no need for `alignLeft` since everything is aligned to the left in SlickGrid
=> feat(formatters): add AlignRight and AlignCenter Formatters

package.json, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/extensionUtility.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/columnPickerExtension.ts, src/app/modules/angular-slickgrid/extensions/extensionUtility.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/shared.service.spec.ts, src/app/modules/angular-slickgrid/services/shared.service.ts, test/cypress/integration/example20.spec.js
- when calling "hide column" we need to readjust the freezingColumn by (-1) when on left container
- when showing/hiding a column from ColumnPicker/GridMenu, we need to check if we need to also readjust when column is on the left container
=> fix(core): showing/hiding column shouldn't affect its freezing position

src/app/modules/angular-slickgrid/formatters/__tests__/complexObjectFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/complexObjectFormatter.ts, src/app/modules/angular-slickgrid/services/__tests__/export-utilities.spec.ts, src/app/modules/angular-slickgrid/services/export-utilities.ts
- when dealing with complex object, it could in some cases return an empty object when targeted object is undefined or not part of the object itself
=> fix(exports): when cell value is empty object return empty string

src/app/examples/grid-graphql-nopage.component.ts, src/assets/lib/multiple-select/multiple-select.js
- `autoAdjustDropPosition` option should not only adjust top/bottom, it should also adjust left/right
=> feat(filters): add auto position (left/right) to multiple-select lib

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- all Editors/Filters are using the column definition id to add a css className for properly identifying the this editor/filter with a unique className, however if the columnId includes a dot then that becomes 2 class names in css and will cause issues, so it's better to advise the user from the start that his column definitions has some invalid Id(s).
=> fix(core): add console error if any of column def id includes dot

src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/models/sorter.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/collection.service.spec.ts, src/app/modules/angular-slickgrid/services/collection.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, src/app/modules/angular-slickgrid/sorters/__tests__/sorterUtilities.spec.ts, src/app/modules/angular-slickgrid/sorters/__tests__/stringSorter.spec.ts, src/app/modules/angular-slickgrid/sorters/dateUtilities.ts, src/app/modules/angular-slickgrid/sorters/numericSorter.ts, src/app/modules/angular-slickgrid/sorters/objectStringSorter.ts, src/app/modules/angular-slickgrid/sorters/sorterUtilities.ts, src/app/modules/angular-slickgrid/sorters/stringSorter.ts
- Some systems like Salesforce sometime remove properties of an object if it's detected as null and this becomes undefined in slickgrid, add a  global grid options to deal with these undefined properties
=> fix(sorting): add cellValueCouldBeUndefined in grid option for sorting

src/app/examples/grid-range.component.ts, src/app/modules/angular-slickgrid/filters/__tests__/sliderRangeFilter.spec.ts, src/app/modules/angular-slickgrid/filters/dateRangeFilter.ts, src/app/modules/angular-slickgrid/filters/sliderRangeFilter.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts
=> fix(core): range default should be inclusive instead of exclusive

src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts
* Improved escaping/normalizing search terms for string/text/readonly fields.
* Invalid characters from integer/float/number fields with string search terms are now removed.
* Added support for range filter `..` to function without an upper bound. When for example `2..` is input then `field GE 2` or `field GT 2` is send to the backend, depending on the `defaultFilterRangeOperator`
* Added support for range filter `..` to function without a lower bound. When for example `..2` is input `field LE 2` or `field LT 2` is send, depending on the `defaultFilterRangeOperator`
- ref issue #656
=> fix(backend): GraphQL queries with input filter

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
=> fix(plugins): throw when Tree Data used with Pagination, closes #658

src/app/modules/angular-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/extensionUtility.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/columnPickerExtension.ts, src/app/modules/angular-slickgrid/extensions/extensionUtility.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts
- when using ColumnPicker, GridMenu or hiding a column via HeaderMenu, it has to recalculate the frozenColumn index because SlickGrid doesn't take care of that and the previous fix that I implement sometimes become out of sync. This PR simplifies the frozenColumn index position, it will simply update it when the index is different, as simple as that.
=> fix(pinning): recalculate frozen idx correctly when column shown changes

src/app/modules/angular-slickgrid/services/__tests__/export.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts
- the custom width was not applied to the correct column, when user had a custom width on column 1 it was applied to column 2. The bug was that getGrouping() always return an array and we should check for its length instead (not just if it exist)
=> fix(exports): Excel Export custom width applies the width to next column

package.json, src/app/modules/angular-slickgrid/models/slickDataView.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- ref SlickGrid new bulk transaction [PR](https://github.com/6pac/SlickGrid/pull/572)
=> feat(services): add bulk transactions in Grid Service CRUD methods

src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/extension.service.ts, test/cypress/integration/example03.spec.js, test/cypress/package.json
=> fix(plugin): recreate header menu w/adding column dynamically, fix #689

src/app/modules/angular-slickgrid/formatters/__tests__/dateEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateIsoFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeEuroAmPmFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeIsoAmPmFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeIsoFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeShortEuroFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeShortIsoFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeShortUsFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeUsAmPmFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateTimeUsFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/__tests__/dateUsFormatter.spec.ts, src/app/modules/angular-slickgrid/sorters/dateUtilities.ts
Here's a quick perf date sorting test before & after code change with 50k rows and 8 columns
_note: the date are all in ISO format (yyyy-mm-dd), it might be even bigger differences with non-ISO format_
sorting ASC: 2255.841064453125 ms
sorting DESC: 676.7099609375 ms
sorting ASC: 644.962646484375 ms
sorting DESC: 671.908935546875 ms
sorting ASC: 1981.27978515625 ms
sorting DESC: 692.999755859375 ms
sorting ASC: 673.643798828125 ms
sorting DESC: 670.118896484375 ms
sorting ASC: 1059.22802734375 ms
sorting DESC: 126.10400390625 ms
sorting ASC: 336.77685546875 ms
sorting DESC: 143.007080078125 ms
sorting ASC: 903.991943359375 ms
sorting DESC: 143.51708984375 ms
sorting ASC: 374.537109375 ms
sorting DESC: 117.73583984375 ms
=> feat(perf): improve date sorting speed

src/app/modules/angular-slickgrid/filter-conditions/__tests__/collectionSearchFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/__tests__/filterUtilities.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/executeMappedCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/filterUtilities.ts, src/app/modules/angular-slickgrid/models/operatorType.enum.ts
- using indexOf returns true whenever the substring is found within a string and that could cause issue, for example "Task1" will be found in "Task123" but that shouldn't be accepted
- also enforce the fact that `IN_CONTAINS` and `NOT_IN_CONTAINS` only works with CSV string "Task 1,Task2"
=> fix(filters): don't use indexOf NOT_IN_CONTAINS

src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts
- add an extra collection length check before rendering the Select Editor/Filter dropdown to avoid multiple-select.js throwing errors that it can't find list or items
=> fix(filters): make sure Select Editor/Filter collection is filled

src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- calling `highlightRow(0)` was not highlighting the row when it should
=> fix(helpers): should be able to highlight first row (0)

src/app/modules/angular-slickgrid/filter-conditions/__tests__/dateIsoFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/__tests__/numberFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/dateFilterCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/numberFilterCondition.ts, src/app/modules/angular-slickgrid/models/filterConditionOption.interface.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, test/cypress/integration/example12.spec.js
- when using 2 dots notation (`2..5`), we should use `defaultFilterRangeOperator` when none is provided and/or isn't a range operator
=> fix(filters): use defaultFilterOperator in range when none provided

src/app/modules/angular-slickgrid/filter-conditions/__tests__/dateIsoFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/__tests__/numberFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/dateFilterCondition.ts, src/app/modules/angular-slickgrid/filter-conditions/numberFilterCondition.ts, src/app/modules/angular-slickgrid/models/filterConditionOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/extension.service.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, test/cypress/integration/example12.spec.js
- there is no need to recreate the header button because if we do that then we lose previous ref and onCommand stops working
=> fix(plugins): do not recreate header button plugin after re-render

src/app/examples/grid-colspan.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/shared.service.spec.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts, src/app/modules/angular-slickgrid/services/shared.service.ts
- the steps to reproduce the issue was to create a grid with `frozenColumn` in the grid options, then change column position (cols reordering) and finally open header menu and freeze any of the column and the bug was that it was going back to original positions while it should keep new positions and just add new freeze column
=> fix(pinning): reordering cols position freezing cols shouldn't affect

package.json, src/app/modules/angular-slickgrid/constants.ts, src/app/modules/angular-slickgrid/filter-conditions/__tests__/stringFilterCondition.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/stringFilterCondition.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundInputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/models/locale.interface.ts, src/assets/i18n/en.json, src/assets/i18n/fr.json, test/cypress/integration/example17.spec.js, test/cypress/package.json
- prefixing a text search with `<>` should be equivalent to "Not Contains" instead of "Not Equal", we can keep the `!=` as "Not Equal" so this way we have both available
=> fix(filters): string <> should be Not Contains instead of Not Equal

src/app/modules/angular-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/models/autocompleteOption.interface.ts
- since user cannot override the jQueryUI `select` callback (because that would break Angular-Slickgrid code), we can instead provide an extra callback, `onSelect`, to do the same with even more arguments
=> feat(editors): add `onSelect` callback to Autocomplete Editor

src/app/modules/angular-slickgrid/filters/__tests__/inputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/services/filter.service.ts
- a use case that we have with the text InputFilter is that if have a filter that includes an operator inside the search text (e.g.: ">=55") and we save the Grid State in Local Storage or anything else and then we reload them as Grid Presets, the operator won't be showing up (it would only show "55" while keeping the Operator hidden but still in play) that is because the FilterService is doing the split (this is an Operator and these are the SearchTerm) and the Grid State only keeps the split, so in that case this PR adds an extra step that if we're using the `setValues()` method, then we're probably using a Grid Preset or an UpdateFilters and we should display the operator as part of the final displayed search string inside the input value
=> feat(filters): display operator into input text filter from Grid Presets

src/app/examples/grid-draggrouping.component.ts, src/app/examples/grid-grouping.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundInputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputMaskFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputNumberFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputPasswordFilter.spec.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/filters/inputMaskFilter.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/backendServiceApi.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- we previously had the `filterTypingDebounce` but that was only available when using `BackendServiceApi` (with OData/GraphQL) but this PR goes further and makes it available to any type of grids, so it can now be used with a local grid (JSON dataset)
- we also move the debounce code from the Filter Service into each filter component itself (only the following 2 filters requires this, `InputFilter` and `CompoundInputFilter`). The Filter Service shouldn't do any debounce, it should be the responsability of the concerned filter and that is what we refactored in this PR as well.
=> feat(filters): add optional `filterTypingDebounce` for filters w/keyup

src/app/examples/grid-state.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/constants.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/models/currentPinning.interface.ts, src/app/modules/angular-slickgrid/models/gridMenu.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/models/gridState.interface.ts, src/app/modules/angular-slickgrid/models/gridStateChange.interface.ts, src/app/modules/angular-slickgrid/models/gridStateType.enum.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/locale.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts, src/assets/i18n/en.json, src/assets/i18n/fr.json, test/cypress/integration/example15.spec.js, test/cypress/integration/example16.spec.js, test/cypress/integration/example20.spec.js, test/translateServiceStub.ts
=> feat(state): add Pinning (frozen) to Grid State & Presets

src/app/modules/angular-slickgrid/filters/__tests__/compoundDateFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundInputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundSliderFilter.spec.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundSliderFilter.ts, src/app/modules/angular-slickgrid/models/columnFilter.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/operatorDetail.interface.ts
- fixes #733
- see [Wiki - Custom Compound Operator List](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Compound-Filters#compound-operator-list-custom-list)
=> feat(filters): option to add custom compound operator list, fix #733

src/app/examples/grid-resize-by-content.component.html, src/app/examples/grid-resize-by-content.component.ts, test/cypress/integration/example30.spec.js
- a quick description of the problem, by default the auto-resize will call the `grid.autosizeColumns()` which will try to find all columns in the grid viewport and that works ok with a small grid but as soon as we have many columns, it starts to wrap many words (with ellipsis) and some user might prefer to resize the column by the cell content (to match the content width with the cell width) and that might mean going wider than the grid viewport.
- so this will be an opt-in feature since it will loop through the entire dataset (by default it will read no more than the first 1000 rows) and find/calculate the width it needs to show the entire text value without word being wrapped, in some cases when having many columns it might make the grid wider than the viewport (in that case the …
=> refactor: use bootstrap radio button group

src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss
- by using directly the unicode character we can make it monochrome instead of having a completely different styling between browsers (chrome was gray while firefox was previously colored, now they both look exactly the same monochrome icon)
=> fix(styling): add better search filter magnify glass icon placeholder

src/app/modules/angular-slickgrid/extensions/__tests__/extensionUtility.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/extensionUtility.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridMenu.interface.ts, src/app/modules/angular-slickgrid/models/gridMenuLabel.interface.ts, src/app/modules/angular-slickgrid/models/index.ts
- prior to the change, we couldn't change the label, we would only be able to change the translation key but we couldn't change the text when we're not using translations. This PR provides both way of customizing these labels, via its label and/or with a label translation key
=> feat(addon): provide grid menu labels for all built-in commands

package.json, src/app/modules/angular-slickgrid/editors/__tests__/checkboxEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/selectEditor.spec.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/services/gridEvent.service.ts, src/assets/lib/multiple-select/multiple-select.js
=> fix(editors): select editor inline blur save before destroy, fixes #752

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/utilities.spec.ts, src/app/modules/angular-slickgrid/services/resizer.service.ts, src/app/modules/angular-slickgrid/services/utilities.ts
- in many cases doing a resize by content only the first time we get data is enough (default is true) and so this flag will handle that scenario or else if the user always want to resize anytime the data changes then the user could disable this new flag
=> feat(resizer): add `resizeByContentOnlyOnFirstLoad` grid option

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts
- loading of Columns Grid Presets should only be done once (before resizing) and loading Filters Grid Presets could be done one or more times, so to fix this I have separated `loadPresetsWhenDatasetInitialized` into 2 new methods and made sure to call the columns grid preset only once.
- this issue was identified while porting the previous PR #341 into Angular-Slickgrid
=> fix(resizer): remove delay to call resize by content to avoid flickering

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/headerMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- with Tree Data only supporting single sort, I found out that we could bypass the single sort by using the header menu
- also found that sort presets with multiple columns were also loading as multiple sort even when the multiColumnSort is disabled and now it's fixed
=> fix(sorting): multi-column sort shouldn't work when option is disabled

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/models/backendService.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/graphql.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts, test/cypress/integration/example06.spec.js
- the backend services were using SlickGrid `getColumns` to get the column definitions but that returns only the visible columns, however we should be able to preset filters on hidden columns and also expect all columns to be queried (it's not because the column is hidden that we shouldn't be able to filter it and query it)
=> fix(backend): able to preset filters on hidden columns & all queried

src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts, test/cypress/integration/example17.spec.js, test/cypress/integration/example27.spec.js
- grid state should only be allowed to change row selection only when Pagination is enabled
- refactor some part of the code to use more optional chaining (?.) syntax for cleaner and smaller code
- move around some of the Cypress tests so that it makes sure that moving rows will keep row selections
=> fix(demo): we should be able to move row(s) and keep selections

src/app/modules/angular-slickgrid/filter-conditions/__tests__/filterUtilities.spec.ts, src/app/modules/angular-slickgrid/filter-conditions/filterUtilities.ts
- fixes a bug reported in SlickGrid [issue 611](https://github.com/6pac/SlickGrid/issues/611)
with the fix, it now returns the correct rows in the grid, but without the fix this was returning nothing
=> fix(filters): filtering with IN_CONTAINS should also work with spaces

src/app/modules/angular-slickgrid/editors/__tests__/selectEditor.spec.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/__tests__/selectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/services/domUtilities.ts, src/app/modules/angular-slickgrid/services/index.ts
- instead of building the select dom element via a string and jQuery. We could instead create these select options as native DOM elements and from there create the jQuery element which the multiple-select.js lib requires. This rewrite should provide a decent performance improvement (especially if we have a huge set of options and will avoid allocating memory for a string that could be come extremly long to hold all the select options for example "<select><option value="true" label="True">True</option>...</select>")
=> feat(filters): build multiple-select options from native dom elements

src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
- calling an update of an row item that is a parent item (with collapse/expand icon) should keep their icon even after an update, it was losing the icon because the Tree structure gets lost and we need to recreate it
=> fix(tree): calling updateItems should not lose the Tree collapsing icon

package.json, src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/rowMoveManagerExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/rowMoveManagerExtension.ts, src/app/modules/angular-slickgrid/models/rowMoveManager.interface.ts
this fixes a problem caught with our current project, we shouldn't call a Save if we're dropping the row at the exact same place it originated from, see animated gif for explanation
(we can see blue line appears even when we didn't really move the row)
(blue line doesn't appear if we don't end up moving the row since the position is the same)
=> fix(plugin): row move shouldn't go further when onBefore returns false

src/app/modules/angular-slickgrid/editors/longTextEditor.ts
- the previous commit to convert jQuery to vanilla JS brought a small issue that was only noticeable when defining a fixed grid height, when that was set and user clicked on the textarea editor it will scrolling to the bottom of the page. This happened because the textarea must be created on the body instead of within the grid and we do a re-positioning of the DOM element to the position of the cell, and the issue was because we focus/select the text content right after it was created (before re-positioning it) and so it was going to the bottom for that reason, we simply need to re-position it BEFORE focusing/selecting the text content
=> fix(editors): longText Editor (textarea) was scrolling to page bottom

package.json, src/app/modules/angular-slickgrid/styles/_private.scss, src/app/modules/angular-slickgrid/styles/sass-utilities.scss, yarn.lock
- The latest version of Dart-Sass prints a bunch warnings when the division operator is used. These changes migrate us to the recommended `math.div` function and won't break users that aren't using latest Dart-Sass yet
- use the same technique as Angular UI from shown in this [PR](https://github.com/angular/components/commit/a4043f41f539ed910c80c780e1815f5625282b94) from them
=> chore(styling): add polyfill to latest dart-sass warnings with division

src/app/modules/angular-slickgrid/services/__tests__/treeData.service.spec.ts, src/app/modules/angular-slickgrid/services/treeData.service.ts
- if we defined `initiallyCollapsed` as true, we should expect the internal toggle state change to be updated accordingly
- also add extra arguments to the `applyToggledItemStateChanges()` method to skip a full toggle and also another argument to optionally trigger an item toggled event
=> fix(tree): using `initiallyCollapsed` change internal toggled state

src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts
- the issue found was with Row Selection when it is not at position 0, the previous code was always assuming that it was at column index 0 but sometime it's not (like our LIG project). Since Row Selection column is added dynamically, this code make sure that when we change dynamically the column position, we will still include the row selection column if it wasn't part of the array provided
=> fix(state): Grid View/Columns dynamically should work w/row selection

src/app/examples/grid-rowmove.component.ts, src/app/modules/angular-slickgrid/services/__tests__/extension.service.spec.ts, src/app/modules/angular-slickgrid/services/extension.service.ts
- providing columnIndexPosition should work regardless of when the extension (plugin) is created, basically the previous code was assuming that you will always want the checkbox before the row move plugin but that is not always true and the other way around wasn't possible while this PR fixes it
=> fix(addon): providing columnIndexPosition should always work

src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts
- when toggling the filter bar (on and off), the horizontal scroll could become out of sync (the alignment of the filters with the column and its data), this happen because the filters are recreated every time we toggle back the filter bar, for that issue we simply need to move the horizontal scroll back to top-left and that fixes the issue
- this bug was reported over Stack Overflow with this [SO question](https://stackoverflow.com/questions/67986388/angular-slickgrid-column-filter-box-alignment-issue)
animated gif of the issue
=> fix(menu): toggle filter bar could be out of sync w/horizontal scroll

src/app/modules/angular-slickgrid/components/__tests__/slick-vanilla-utilities.spec.ts, src/app/modules/angular-slickgrid/components/slick-vanilla-utilities.ts
- basically if our Custom Editor Formatter is already in the column definitions and we re-ran `autoAddEditorFormatterToColumnsWithEditor` method for any reasons (this happen when changing column definitions via its setter) then we want to make sure that we don't add the same formatter over and over
below is an example of the bug when it happens, we can see the editor formatter (the cell with outlines) are added multiple times and show multiple outlines
and after the fix, we now see the outline only once because the editor formatter will never be added more than once
=> fix(formatters): shouldn't auto-add editor formatter multiple times

src/app/modules/angular-slickgrid/styles/slick-grid.scss
- column header titles that are too long should show the "..." ellipsis and that was not working because it's a bit different with text over multiple lines
=> fix(styling): header title should show ellipsis if too long

src/app/modules/angular-slickgrid/services/__tests__/excelExport.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/export.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts, src/app/modules/angular-slickgrid/services/export.service.ts
- partially relate to discussion #763 to totally skip expanded Row Detail panel from the export
=> fix(export): expanded Row Detail shouldn't be exported

src/app/modules/angular-slickgrid/components/slick-pagination.component.ts, src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, test/cypress/integration/example10.spec.js
- we should be able to toggle Pagination and it should still work as expected after showing it again
- the previous code was disposing of the Pagination Service when hiding (disposing) the Pagination Component but that shouldn't be the case, disposing of the Service should strictly be handled by the Angular-Slickgrid-Component
=> fix(pagination): should be able to toggle Pagination

src/app/modules/angular-slickgrid/filter-conditions/stringFilterCondition.ts
=> fix(filters): startsWith/endsWith operator should work, fixes #811

src/app/modules/angular-slickgrid/formatters/__tests__/complexObjectFormatter.spec.ts, src/app/modules/angular-slickgrid/formatters/complexObjectFormatter.ts
fixes a bug reported in this Stack Overflow question _[angular slick grid complex object with nullable string
](https://stackoverflow.com/questions/68449432/angular-slick-grid-complex-object-with-nullable-string)_
=> fix(formatters): Complex Object Formatter shouldn't throw with null data

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- fixes Slickgrid-Universal issue [#469](https://github.com/ghiscoding/slickgrid-universal/issues/469)
- we should always use DataView `getFilteredItemCount()` since that is really the item count that we want to show in the footer `getFilteredItemCount` to show correct count, fix #469
- fixes #469
- we should always use DataView `getFilteredItemCount()` since that is really the item count that we want to show in the footer
=> fix(footer): use `getFilteredItemCount` to show correct item count

test/cypress/integration/example30.spec.js
- fix an issue in Slickgrid-Universal which we found that if we Edit a value (let say Title to "Task 1234") and then do a Mass Update on different field (say "% Complete" to 90%), the mass update was actually picking up the "Task 1234" from the previous edit even though it wasn't part of the Mass Update. So we can simply clear the `formValues` object when opening the modal window and before populating the form
=> fix(composite): calling Edit change shouldn't affect Mass-Update

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
This is "PR 2" as mentioned here https://github.com/ghiscoding/Angular-Slickgrid/issues/836
This removes the  `bindAutoResizeDataGrid()` call from `bindResizeHook` as its already called from `resizerService.init`. 
In Slickgrid vanilla & Aurelia it's also not done from `bindResizeHook`.
I have run all unit & cypress tested and tested some resizes manually and all look good.
=> fix(resizer): remove redundant bindAutoResizeDataGrid call

package.json, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts, yarn.lock
- the EventPubSubService is providing EventSubscription, not RxJS Subscription, so we should use unsubscribe the correct subscription type
- also bump required RxJS version since it seems to throw some type error on the RxJsFacade of Slickgrid-Universal which recently got bumped as well
=> fix(build): should use `EventSubscription` to be unsubscribed

package.json, yarn.lock
- original package does not seem to be updated anymore and `npm-run-all2` was created for that reason to be up to date
=> chore(build): replace `npm-run-all` with `npm-run-all2`

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- should throw if 1 of these 2 are missing `[gridOptions]` and/or `[columnDefinitions]`
- fixes #910
=> fix(core): throw error when `[gridOptions]` missing, fixes #910

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, yarn.lock
- replicate issue found and fixed in Slickgrid-Universal [PR 742](https://github.com/ghiscoding/slickgrid-universal/pull/742)
=> fix(collectionAsync): hidden column does not load edit field selection

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, test/cypress/cypress.config.js, test/cypress/e2e/example16.cy.js
- the steps to reproduce the issue was to create a grid with `frozenColumn` in the grid options, then change column position (cols reordering) and finally open header menu and freeze any of the column and the bug was that it was going back to original positions while it should keep new positions and just add new freeze column
=> fix(pinning): cols reorder & freezing shouldn't affect order

src/app/examples/grid-autoheight.component.scss, src/app/examples/grid-autoheight.component.ts
- add margin on the last column so that sort icon & header menu doesn't fall behind the grid menu
=> chore: add Grid Menu styling to grid with `autoHeight`

src/app/examples/custom-angularComponentEditor.ts, src/app/examples/custom-angularComponentFilter.ts, src/app/examples/grid-contextmenu.component.ts, src/app/examples/grid-graphql.component.ts, src/app/examples/grid-headermenu.component.ts, src/app/examples/grid-localization.component.ts, src/app/examples/grid-menu.component.ts, src/app/examples/grid-range.component.ts, src/app/examples/grid-state.component.ts, src/app/modules/angular-slickgrid/services/utilities.ts
- let's not use RxJS Subscription directly to avoid errors when upgrading RxJS, for example this error is caused by a version mismatch between Angular-Slickgrid and the demos: "Type 'import("...dist/types/internal/Subscription").Subscription[]' is not assignable to type 'import(".../dist/types/internal/Subscription").Subscription[]'."
=> fix(rxjs): make unsubscribe more generic to avoid RxJS update issue

src/app/examples/grid-rowmove.component.ts, src/app/examples/swt-common-grid.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/angularGridInstance.interface.ts, src/app/modules/angular-slickgrid/models/externalTestingDependencies.interface.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/models/rowDetailView.interface.ts, src/app/modules/angular-slickgrid/models/slickGrid.interface.ts, src/app/modules/angular-slickgrid/modules/angular-slickgrid.module.ts, src/app/modules/angular-slickgrid/services/angularUtil.service.ts, src/app/modules/angular-slickgrid/services/container.service.ts, src/app/modules/angular-slickgrid/services/translater.service.ts, src/app/modules/angular-slickgrid/slickgrid-config.ts
- fixes issues found while developing with the new Angular 16 esbuild experimental, esbuild was throwing the following error
> No matching export for types exported via ...
and the answer is simply to add the `import type` on interfaces as mentioned in this esbuild issue
https://github.com/evanw/esbuild/issues/1941#issuecomment-1028157800
=> fix: using esbuild requires to specify type imports

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- calling `datasetHierarchical` setter shouldn't cause scroll flickering, this was caused a call to the DataView `setItems` with an empty array which in terms always scroll back to top and that was meant to clear the dataset before recreating it, however this is certainly not needed since calling the `datasetHierarchical` setter will then trigger a new sort which will indirectly call DataView setItems anyway
- it might also fix issue #1201, I'm not entirely sure since the user never mentioned which type of Tree Data (there's 2 types) was used
=> fix: adding dataset hierarchical item shouldn't cause scroll flickering

.github/ISSUE_TEMPLATE/bug_report.yml, src/app/examples/custom-angularComponentFilter.ts, src/app/examples/grid-angular.component.ts, src/app/examples/grid-remote.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts, src/app/modules/angular-slickgrid/modules/angular-slickgrid.module.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/angularUtilService.spec.ts, src/app/modules/angular-slickgrid/services/angularUtil.service.ts, test/jest.config.ts
- because we used `setTimeout` in Example 22, it was creating the dynamic Component and rendering it at the bottom of the DOM, in our case just after the grid at the bottom of it before then transition it (or moving the DOM element) to the cell target. However we shouldn't need a `setTimeout` at all if we use `cd.detectChanges()` BUT we need to move this code into the util method that creates the component because we need to detect changes right after changing the instance data BUT before getting or reading the new Component HTML... so this way we can drop the `setTimeout` and we just use  `cd.detectChanges()` inside the util (which is even better since it simplifies the user code a lot) and this should improve performance by 2x every cell rendering because we no longer need to wait a …
=> feat: improve AngularUtilService methods to create dynamic component, fixes #1273

.github/workflows/main.yml, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- fixes a regression brought up in issue #1329 even though the issue was brought for the new v7, this regression was also pushed on last v6.6.5 so a fix is necessary on v6 as well
=> fix: externalResouces should also work globally

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- fixes issue #1329
- external resources can also be loaded globally in the forRoot and that regressed in previous PR #1320
=> fix: regression externalResouces should work globally, fix #1329

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/examples/grid-header-footer.component.html, src/app/examples/grid-header-footer.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.html, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, test/cypress/e2e/example34.cy.ts
This adds the ability to define a custom header and footer via ng-templates.
The feature is already present in Aurelia-Slickgrid (https://ghiscoding.github.io/aurelia-slickgrid/#/example29) and by so just a port for Angular-Slickgrid, using Angular native constructs
closes #1335
=> feat: custom header and footer

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- when loading a new grid, we are calling `grid.autosizeColumns()` to resize the columns and while adding tests for that method I incidently discovered that it was being called multiple times on a page load (up to 6-8x times) but in reality there is no need to call it more than once or twice.
- there is also no need to call the `autosizeColumns` if the grid dimension calculated by the Resizer Service are the same as the previously calculated dimensions
- the updated code will never call `autosizeColumns` more than twice on a page load, however note that the method will always be called whenever the grid dimensions or columns get updated
=> perf(resizer): `autosizeColumns` is called too many times on page load

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.html
- we shouldn't use inline `style` for CSP safe code, that code was moved in Slickgrid-Universal style instead
=> fix: remove width style on grid container for CSP safe, fixes #1368

docs/column-functionalities/filters/custom-filter.md, docs/migrations/Migration-to-2.x.md, src/app/examples/custom-angularComponentEditor.ts, src/app/examples/custom-angularComponentFilter.ts, src/app/examples/grid-angular.component.ts, src/app/examples/grid-clientside.component.ts, src/app/examples/grid-range.component.ts
- the Filter `model` prop should be a constructor and it shouldn't newed (instantiated), it was defined like so in the docs and Wikis but that was actually wrong
- ref Slickgrid-Universal [PR 1430](https://github.com/ghiscoding/slickgrid-universal/pull/1430)
=> fix: Filter `model` is now `FilterConstructor` and shouldn't be newed

src/app/examples/grid-draggrouping.component.html, src/app/examples/grid-draggrouping.component.ts
- to answer a Stack Overflow [question](https://stackoverflow.com/q/78180503/1212166) on how to update aggregated totals after an edit, we need to call `dataView.refresh()` for the Aggregators to have updated value(s)
=> chore(demo): add edit cell demo in Draggable Grouping example

src/app/examples/custom-angularComponentEditor.ts, src/app/examples/custom-inputEditor.ts, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- users can still call `internalColumnEditor` but since it's deprecated, then it's better to remove it from all demos
=> chore: remove deprecated `internalColumnEditor` usage

src/app/examples/grid-base-row-editing.component.ts, src/app/examples/grid-composite-editor.component.ts, src/app/examples/grid-custom-tooltip.component.scss, src/app/examples/grid-custom-tooltip.component.ts, test/cypress/e2e/example30.cy.ts, test/cypress/e2e/example32.cy.ts, test/cypress/e2e/example35.cy.ts, test/mockSlickEvent.ts
- for some unknown reasons the tooltips are shown correctly in the browser but not in Cypress, I had to use a few force click
=> fix: allow multiple tooltips per grid cell

package.json
- SortableJS is already required by Slickgrid-Universal and is only used by Jest in Angular-Slickgrid, so it should be moved to dev deps for that reason.
=> chore(deps): move SortableJS as dev deps

src/app/examples/grid-tree-data-parent-child.component.html, src/app/examples/grid-tree-data-parent-child.component.ts
closes issue #1423 
- prior to this PR, calling `addItem()`, or `addItems()`, was always resorting using the Tree Data initial sort because the method being called is the same for the first build of the Tree Data and/or adding an item. So when we're adding an item, we should really reuse any existing sort that may exist when resynching the flat/hierarchical and resorting them (we always need to resort whenever it changes because by SlickGrid doesn't support Tree Data, we only support it by keeping copies of both flat & hierarchical and then resort them whenever something changes)
=> fix(TreeData): addItem should keep current sorted column

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
When navigating away from within a rowdetail-view component the browser logs `NG0406: This instance of the ApplicationRef has already been destroyed` in the console.
Steps to reproduce & validate the fix:
rowdetail-view.component.html
```html
<button class="btn btn-outline-secondary btn-sm" (click)="navigate()" data-test="navigate-btn">
Navigate to Basic Grids
</button>
```
rowdetail-view.component.ts
```ts
export class RowDetailViewComponent {
private readonly _router = inject(Router);
...
navigate() {
this._router.navigate(['/basic']);
}
}
```
The issue is caused by the `AngularSlickgridComponent` providing the `ApplicationRef` as a transient. Reading up on the `ApplicationRef`, it looks like it should be a singleton provided by Angular itself.
I didn't include the above changes to …
=> fix: NG0406: This instance of the ApplicationRef has already been destroyed

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
fixes comment mentioned in separate PR #1457 
> Also I noticed that `SlickRowDetailView.dispose` is called 2x. The 1st time from:
> 
> ```ts
> this.serviceList.forEach((service: any) => {
>       if (service && service.dispose) {
>         service.dispose();
>       }
>     });
> ```
> 
> And the 2nd from
> 
> ```ts
> // dispose all registered external resources
> this.disposeExternalResources();
> ```
> 
> I'm not sure if that is intended behavior?
The issue was because both the `externalResources` & `extensionList` are arrays and to make it easier, they both loop through their arrays when it's time to dispose (destroy) of them. However the `RowDetailService` was added to both arrays which was disposing of it twice instead of once. This PR fixes this by keeping RowDetail in the …
=> fix: register RowDetail and dispose of it only once

src/app/examples/grid-draggrouping.component.ts, src/app/examples/grid-grouping.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- see this Slickgrid-Universal [comment](https://github.com/ghiscoding/slickgrid-universal/issues/1678#issuecomment-2349071503) for more details
=> perf: don't invalidate grid rows more than once

src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts
=> fix: redraw all open row details whenever the grid is re-rendered

src/app/examples/swt-common-grid-pagination.component.ts, tsconfig.json
as per this article: https://blog.angular.dev/using-isolatedmodules-in-angular-18-2-68a7d3a6c03d
=> chore: try enabling TS isolatedModules

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- we should be able to use Angular-Slickgrid component without providing any grid options
=> feat: allow using AngularSlickgrid component w/o grid options

angular.json, docs/getting-started/troubleshooting.md, package.json, src/app/examples/grid-editor.component.ts, src/app/examples/grid-remote.component.ts, src/app/examples/jsonp.ts, yarn.lock
- rewrite fetch-jsonp as ESM but only locally since this is only used for demo purposes
=> chore: localize fetch-json to avoid importing old CJS package

src/app/examples/grid-tree-data-hierarchical.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/global-grid-options.ts
=> fix: add `autoResize.autoHeight` to resize by dataset length

src/app/examples/rowdetail-preload.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts
=> fix: Row Detail preload comp should call destroy lifecycle, fixes #589

docs/grid-functionalities/Grid-Menu.md, docs/grid-functionalities/Grid-State-&-Preset.md, docs/grid-functionalities/Row-Selection.md
in migration to v2 
```
- Event Emitter `(onGridStateServiceChanged)` renamed to `(onGridStateChanged)`
```
I got confused why the event did not work
=> fix(docs): update onGridStateServiceChanged to onGridStateChanged
