src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/examples/swt-common-grid-pagination.component.ts, src/app/examples/swt-common-grid-test.component.html, src/app/examples/swt-common-grid-test.component.ts, src/app/examples/swt-common-grid.component.ts, src/app/examples/swt-logger.service.ts
Dear Ghislan, 
As promised, this is the custom pagination component that is separated from the AngularSlickgridComponent.
Filtering and Sorting are done on server side.
No Promises are used.
Request url is appended this way:
`currentPage=2&selectedSort=5|true|&selectedFilter=All|All|All|All|All|JOD|All|All|All|All|All|All|`
This means, we are requesting for page nbr 2, making a sort over column nbr 5, ASC=true and filtering the content of the 6th column by value JOD.
It can be written the way developer wants it.
=> New custom pagination component

src/app/examples/grid-clientside.component.html, src/app/examples/grid-clientside.component.ts, src/app/examples/grid-graphql.component.html, src/app/examples/grid-graphql.component.ts, src/app/examples/grid-odata.component.html, src/app/examples/grid-odata.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.ts, src/app/modules/angular-slickgrid/models/graphqlResult.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/statistic.interface.ts, src/app/modules/angular-slickgrid/services/controlAndPlugin.service.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- also do an example on local dataset and dataview trigger in client example
=> feat(telemetry): add telemetry statistics to backendServiceApi

src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/nativeSelectFilter.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/formatters/collectionEditorFormatter.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts, src/app/modules/angular-slickgrid/models/columnFilter.interface.ts
- prior to this only collection of value/label pair was accepted.
=> feat(select): collection can also be of type String

src/app/examples/grid-clientside.component.ts, src/app/examples/grid-remote.component.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputNumberFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputPasswordFilter.ts, src/app/modules/angular-slickgrid/filters/index.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/filters/inputNumberFilter.ts, src/app/modules/angular-slickgrid/filters/inputPasswordFilter.ts
- add these new types to InputFilter & CompoundInputFilter
- `compoundInputText` (alias of `compoundInput` Filter)
- `compoundInputNumber`
- `compoundInputPassword`
- `inputText` (alias of `input` Filter)
- `inputNumber`
- `inputPassword`
=> feat(inputType): Add multiple filter input types (number/password)

package.json, src/app/examples/grid-odata.component.ts, src/app/examples/grid-rowselection.component.ts, src/app/modules/angular-slickgrid/models/checkboxSelector.interface.ts, src/app/modules/angular-slickgrid/styles/slick-plugins.scss
- provide 2 flags to change "Select All" checkbox location, it could be displayed in Column Header Row (default) or now also in Filter Row.
=> feat(selector): add new property to display Select All chkbox elsewhere

src/app/examples/grid-headerbutton.component.ts, src/app/examples/grid-headermenu.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts
- moved the debounce into the FilterService so it's no longer required to implement in each backend services
=> fix(backend): debounceTypingDelay on input Filter was no longer

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/examples/grid-rowdetail.component.html, src/app/examples/grid-rowdetail.component.ts, src/app/examples/rowdetail-preload.component.html, src/app/examples/rowdetail-preload.component.ts, src/app/examples/rowdetail-view.component.html, src/app/examples/rowdetail-view.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/extensionUtility.ts, src/app/modules/angular-slickgrid/extensions/index.ts, src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts, src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/models/extensionName.enum.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/rowDetailView.interface.ts, src/app/modules/angular-slickgrid/services/extension.service.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-plugins.scss
Here's an animated gif of the feature
=> feat(RowDetail): add Row Detail Plugin extension, closes #118

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts, src/app/examples/grid-additem.component.html, src/app/examples/grid-additem.component.ts, src/app/examples/grid-angular.component.html, src/app/examples/grid-autoheight.component.html, src/app/examples/grid-autoheight.component.ts, src/app/examples/grid-basic.component.html, src/app/examples/grid-draggrouping.component.html, src/app/examples/grid-editor.component.html, src/app/examples/grid-formatter.component.html, src/app/examples/grid-frozen.component.html, src/app/examples/grid-grouping.component.html, src/app/examples/grid-headerbutton.component.html, src/app/examples/grid-headermenu.component.html, src/app/examples/grid-localization.component.html, src/app/examples/grid-menu.component.html, src/app/examples/grid-remote.component.html, src/app/examples/grid-rowdetail.component.html, src/app/examples/grid-rowmove.component.html, src/app/examples/grid-rowselection.component.html, src/app/examples/home.component.html, src/app/modules/angular-slickgrid/models/gridOption.interface.ts, src/app/modules/angular-slickgrid/services/resizer.service.ts
- also add autoHeight Grid Option with Example, that option was missing from the GridOption interface
=> fix(resizer): minHeight, minWidth not working correctly, closes #133

src/app/modules/angular-slickgrid/services/resizer.service.ts
=> fix(autoHeight): ResizerService shouldn't calculates height for any div

src/app/examples/grid-autoheight.component.html, src/app/examples/grid-autoheight.component.ts, src/app/examples/grid-editor.component.ts
- show how to do a single search outside of the grid
=> feat(filter): add demo of single search filter

src/app/modules/angular-slickgrid/editors/dateEditor.ts
- the problem was more around the fact that Flatpickr uses an alternate input (altInput) to display a human friendly date and that was not the input being focused and so user couldn't backspace because it wasn't in focus
=> fix(dateEditor): allow backspace for deleting a date, close #166

src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/services/utilities.spec.ts, src/app/modules/angular-slickgrid/services/utilities.ts
- add more checks when needed
- renamed arrayEqual to charArraysEqual to represent that it's only working with array of chars
=> feat(tests): add Service Utilities full test suite

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/__tests__/collection.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/gridEvent.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/app/modules/angular-slickgrid/services/gridEvent.service.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- also add coverage to some other tests
=> feat(tests): add GroupingAndColspanService full test suite

src/app/examples/grid-grouping.component.ts, src/app/modules/angular-slickgrid/models/backendService.interface.ts, src/app/modules/angular-slickgrid/models/filter.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/sort.service.spec.ts, src/app/modules/angular-slickgrid/services/backend-utilities.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/sort.service.ts
- refactor SortService to use a common backend function used by FilterService as well
=> feat(tests): add more unit tests to FilterService

src/app/modules/angular-slickgrid/editors/floatEditor.ts
FloatEditor accepts negative number.
=> fix negative number in floatEditor

.circleci/config.yml, .gitignore, CHANGELOG.md, package.json, src/app/examples/custom-angularComponentFilter.ts, src/app/examples/custom-inputFilter.ts, src/app/examples/grid-menu.component.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundDateFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundInputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/compoundSliderFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/dateRangeFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/inputFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/nativeSelectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/selectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/singleSelectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/sliderFilter.spec.ts, src/app/modules/angular-slickgrid/filters/__tests__/sliderRangeFilter.spec.ts, src/app/modules/angular-slickgrid/filters/autoCompleteFilter.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundSliderFilter.ts, src/app/modules/angular-slickgrid/filters/dateRangeFilter.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/filters/inputMaskFilter.ts, src/app/modules/angular-slickgrid/filters/nativeSelectFilter.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/filters/sliderFilter.ts, src/app/modules/angular-slickgrid/filters/sliderRangeFilter.ts, src/app/modules/angular-slickgrid/models/filter.interface.ts
- some of the Filters were not handling well searchTerms that could be the false boolean, this was resulting as not being a searchTerm while in fact it could be a valid entry
- calling "clear filter" on Slider Filter was causing empty grid after being triggered
=> feat(filter): add unit test suite for multiple Filters

src/app/examples/grid-additem.component.html, src/app/examples/grid-additem.component.ts, src/app/modules/angular-slickgrid/models/gridServiceInsertOption.interface.ts, src/app/modules/angular-slickgrid/models/gridServiceUpdateOption.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts
=> feat(insert): add option to insert item at bottom of grid

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.html, src/app/modules/angular-slickgrid/components/slick-pagination.component.ts, src/app/modules/angular-slickgrid/models/angularGridInstance.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/pager.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/graphql.service.ts, src/app/modules/angular-slickgrid/services/grid.service.ts, src/app/modules/angular-slickgrid/services/index.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts
- with this new Service, user can now programmatically change page from its application since the Pagination Service is now exposed to the outside
=> feat(backend): extract Pagination into its own Service to expose methods

src/app/examples/grid-menu.component.ts, src/app/modules/angular-slickgrid/services/__tests__/filter.service.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts
=> fix(filter): should be able to filter even on hidden columns, fixes #310

src/app/examples/grid-graphql.component.html, src/app/examples/grid-odata.component.html, test/cypress/integration/example5.spec.js, test/cypress/integration/example6.spec.js, test/cypress/integration/example9.spec.js, test/cypress/package.json
- also update to latest Cypress version
=> feat(cypress): add Pagination Service E2E tests

src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/app/modules/angular-slickgrid/services/grid-odata.service.ts
=> fix(odata): no single quote escape required for IN operator for non-string column

src/app/examples/grid-basic.component.html, src/app/examples/grid-basic.component.ts, src/app/examples/grid-rowselection.component.html, src/app/examples/grid-rowselection.component.ts, src/app/examples/grid-state.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/__tests__/slick-pagination-without-translate.component.spec.ts, src/app/modules/angular-slickgrid/components/__tests__/slick-pagination.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/checkboxSelectorExtension.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/pagination.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/shared.service.spec.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts, src/app/modules/angular-slickgrid/services/pagination.service.ts, src/app/modules/angular-slickgrid/services/shared.service.ts, src/styles.scss, test/cypress/integration/example01.spec.js, test/cypress/integration/example10.spec.js, test/cypress/integration/example16.spec.js
=> feat(pagination): add Pagination to local grid, closes #338

src/app/examples/custom-inputFilter.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/filters/autoCompleteFilter.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts, src/app/modules/angular-slickgrid/filters/compoundSliderFilter.ts, src/app/modules/angular-slickgrid/filters/dateRangeFilter.ts, src/app/modules/angular-slickgrid/filters/inputFilter.ts, src/app/modules/angular-slickgrid/filters/nativeSelectFilter.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/filters/sliderFilter.ts
- move the element IDs as CSS classes instead
=> fix(filters): remove filter DOM element IDs to avoid duplicate IDs

src/app/examples/grid-rowselection.component.ts, src/app/modules/angular-slickgrid/models/currentRowSelection.interface.ts, src/app/modules/angular-slickgrid/services/__tests__/gridState.service.spec.ts, src/app/modules/angular-slickgrid/services/gridState.service.ts, test/cypress/integration/example10.spec.js
- a new property "filteredDataContextIds" was added to handle possible filtered data with row selection
=> fix(selection): filter data should work with row selection, closes #295

src/app/modules/angular-slickgrid/global-grid-options.ts, src/app/modules/angular-slickgrid/services/__tests__/excelExport.service.spec.ts, src/app/modules/angular-slickgrid/services/__tests__/export.service.spec.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts, src/app/modules/angular-slickgrid/services/export.service.ts, test/cypress/package.json
- when having Grouped Header Titles (in pre-header), those were not showing in the export, now they do
=> fix(export): add grouped header title (from pre-header) into exports

src/app/modules/angular-slickgrid/editors/__tests__/dateEditor.spec.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/models/flatpickrOption.interface.ts
- when user passes a date that is not in the accepted range, Flatpickr will show a warning which should be disregarded completely
=> fix(editor): disregard Date Editor Flatpickr error and fix output format

src/app/examples/grid-basic.component.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
=> fix(pagination): passing custom pagination sizes should work, fixes #456

README.md, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts
previous PR #448 caused a new and small issue, were the header row is being shown when changing locale even when there are no Filters.
=> fix(gridMenu): command "Toggle Filter Row" header row

package.json, src/app/modules/angular-slickgrid/models/gridMenu.interface.ts
- also fixes an issue with grouping header not properly showing full browser vertical scroll
- fixes #464
=> feat(gridMenu): update SlickGrid & add new Grid Menu options, fixes #464

src/app/modules/angular-slickgrid/editors/__tests__/dualInputEditor.spec.ts, src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/utilities.spec.ts, src/app/modules/angular-slickgrid/services/filter.service.ts, src/app/modules/angular-slickgrid/services/grid.service.ts, src/app/modules/angular-slickgrid/services/treeData.service.ts, src/app/modules/angular-slickgrid/services/utilities.ts, test/cypress/package.json
- do a solution search and add "datasetIdPropertyName" everywhere that it was missing
=> fix(core): add missing use of custom datasetIdPropertyName

src/app/examples/grid-additem.component.ts
=> fix(example): use highest id as new id in addItem example, fixes #495

src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid-constructor.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts
=> fix(filter): recreate filter when toggling header row, fixes #493

src/app/app.component.html, src/app/examples/grid-tree-data-hierarchical.component.scss, src/app/modules/angular-slickgrid/editors/selectEditor.ts
- when using boolean with a SingleSelect Editor, the `false` value was not being selected when it should
=> fix(editor): SingleSelect Editor should show pick false value

src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slickgrid-theme-material.scss, src/app/modules/angular-slickgrid/styles/slickgrid-theme-salesforce.lite.scss, src/app/modules/angular-slickgrid/styles/slickgrid-theme-salesforce.scss
- make lite and regular file different, the regular file shouldn't call the lite version since that caused other issues
=> fix(styling): refactor Material/Salesforce styling theme

README.md
This change will add the compatibility list of ngx-translate library for different Angular versions
=> Compatibility list for ngx-translate library

src/app/modules/angular-slickgrid/editors/__tests__/selectEditor.spec.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/filters/__tests__/selectFilter.spec.ts, src/app/modules/angular-slickgrid/filters/selectFilter.ts, src/app/modules/angular-slickgrid/models/collectionOption.interface.ts
- add 2 new methods (`addCustomFirstEntry`, `addCustomLastEntry`) to optionally add entry on both end of the collection
=> feat(core): add custom entry to Select Editor/Filter collections

src/app/modules/angular-slickgrid/components/__tests__/slick-pagination.component.spec.ts, src/app/modules/angular-slickgrid/components/slick-pagination.component.html
Fixes https://github.com/ghiscoding/Angular-Slickgrid/issues/602
=> Select the option with the current itemsPerPage in the select dropdown

package.json, src/app/examples/custom-inputEditor.ts, src/app/examples/grid-formatter.component.ts, src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts, src/app/modules/angular-slickgrid/extensions/__tests__/checkboxSelectorExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/cellExternalCopyManagerExtension.ts, src/app/modules/angular-slickgrid/extensions/checkboxSelectorExtension.ts, src/app/modules/angular-slickgrid/extensions/rowMoveManagerExtension.ts, src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts, src/app/modules/angular-slickgrid/services/grid.service.ts, src/app/modules/angular-slickgrid/services/resizer.service.ts
=> fix(core): properly dispose plugins to avoid detached DOM elements

src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/__tests__/longTextEditor.spec.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/models/index.ts, src/app/modules/angular-slickgrid/models/longTextEditorOption.interface.ts, src/app/modules/angular-slickgrid/styles/_variables.scss, src/app/modules/angular-slickgrid/styles/slick-editors.scss
- add options to change button texts
- add auto position that will automatically find best window position to show textarea
- add options cols/rows to change textarea size
=> feat(editors): add few editor options to LongText (textarea) Editor

src/assets/lib/multiple-select/multiple-select.js
- use the offseft left position to properly calculate the available space instead of the scroll left position
=> fix(filters): use offset left to calculate auto position (left/right)

src/app/modules/angular-slickgrid/extensions/__tests__/contextMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/contextMenuExtension.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts, src/app/modules/angular-slickgrid/services/excelExport.service.ts, src/app/modules/angular-slickgrid/services/export.service.ts
=> fix(exports): should be able to change export file name, fixes #655

src/app/modules/angular-slickgrid/extensions/__tests__/rowDetailViewExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts
- fixes bug reported in this Stack Overflow [question](https://stackoverflow.com/questions/65520443/combination-of-row-detail-view-and-checkboxselector-option-makes-weird-behavior)
=> fix(plugin): Row Detail loses html content when used with Row Selection

package.json, src/app/examples/grid-editor.component.ts, src/app/modules/angular-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/app/modules/angular-slickgrid/editors/__tests__/selectEditor.spec.ts, src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/selectEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts, src/app/modules/angular-slickgrid/models/collectionOverrideArgs.interface.ts, src/app/modules/angular-slickgrid/models/column.interface.ts, src/app/modules/angular-slickgrid/models/columnEditor.interface.ts, src/app/modules/angular-slickgrid/models/index.ts, test/cypress/cypress.json, test/cypress/package.json
- only applies to Editor with collection (autocomplete & single/multiple select)
=> feat(editors): add Column Editor collectionOverride option

package.json, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/filters/compoundDateFilter.ts, src/app/modules/angular-slickgrid/filters/dateRangeFilter.ts
- this is mostly just a precaution, it wasn't throwing any error but it provides a 2nd way to import Flatpickr
=> chore: Flatpickr changed their esm module export

src/app/modules/angular-slickgrid/components/__tests__/slick-empty-warning.spec.ts, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts, src/app/modules/angular-slickgrid/components/slick-empty-warning.component.ts, src/app/modules/angular-slickgrid/models/gridOption.interface.ts
=> fix(comp): empty data warning should work with autoheight grid, fix #671

src/app/modules/angular-slickgrid/editors/autoCompleteEditor.ts, src/app/modules/angular-slickgrid/editors/checkboxEditor.ts, src/app/modules/angular-slickgrid/editors/dateEditor.ts, src/app/modules/angular-slickgrid/editors/dualInputEditor.ts, src/app/modules/angular-slickgrid/editors/floatEditor.ts, src/app/modules/angular-slickgrid/editors/integerEditor.ts, src/app/modules/angular-slickgrid/editors/longTextEditor.ts, src/app/modules/angular-slickgrid/editors/sliderEditor.ts, src/app/modules/angular-slickgrid/editors/textEditor.ts
- also changed all services to readonly
=> feat(editors): change all private keyword to protected for extensability

src/assets/lib/multiple-select/multiple-select.js
- in some rare occasion we had "cannot read 'prop' of undefined" happening. This PR adds more checks to make sure we aren't trying to read a method of an undefined element
=> fix(filters): add more variable undefined checks in multiple-select external lib

package.json, src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
=> fix(metrics): use `onRowCountChanged` event to refresh metrics fix #715

src/app/modules/angular-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/app/modules/angular-slickgrid/extensions/columnPickerExtension.ts, src/app/modules/angular-slickgrid/extensions/gridMenuExtension.ts
=> fix(selection): full row selection should be selected w/show hidden row

src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts
- hopefully help in fixing issue #820
=> fix(grid): invalidate grid after `setItems` to re-render grid

.github/workflows/main.yml
- see this GitHub [comment](https://github.com/actions/runner/issues/1019#issuecomment-808880611)
=> chore: fix CI invalid yml file format [refresh gh-pages]

src/app/app.module.ts, src/app/examples/custom-buttonFormatter.component.ts, src/app/examples/grid-angular.component.ts, src/app/modules/angular-slickgrid/services/__tests__/angularUtilService.spec.ts, src/app/modules/angular-slickgrid/services/angularUtil.service.ts, test/cypress/e2e/example22.cy.ts
Adds an API to create interactive angular components, meaning not destroying them after a single render
fixes #1294
=> feat: interactive angular component api

docs/grid-functionalities/excel-copy-buffer.md
related discussion https://github.com/ghiscoding/Angular-Slickgrid/discussions/1339
=> docs: explain denyPaste property

docs/TOC.md, docs/grid-functionalities/FAQ.md
=> docs: add FAQ for grid functionallity

.browserslistrc, angular.json
- also update browserslist config
=> chore: replace deprecated browserTarget w/buildTarget [refresh gh-pages]

angular.json, package.json, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts
- related to issue described in Angular-Slickgrid: https://github.com/ghiscoding/Angular-Slickgrid/discussions/838#discussioncomment-8574215
=> fix: switch to `isomorphic-dompurify` for SSR support

angular.json, docs/column-functionalities/Formatters.md, docs/column-functionalities/editors/Select-Dropdown-Editor-(single,multiple).md, docs/column-functionalities/filters/Select-Filter.md, docs/developer-guides/csp-compliance.md, docs/getting-started/quick-start.md, package.json, src/app/app.module.ts, src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts, yarn.lock
- replace `isomorphic-dompurify` with `dompurify` and make it a dev deps
=> feat!: make DOMPurify as optional

docs/column-functionalities/filters/Range-Filters.md
=> docs: rename editorOptions to filterOptions

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/examples/grid-footer-totals.component.html, src/app/examples/grid-footer-totals.component.ts, test/cypress/e2e/example37.cy.ts
=> feat: add Footer Totals Row and fix footer styling

docs/testing/testing-patterns.md
Explains how to remount cjs to esm when using vitest
fixes https://github.com/ghiscoding/slickgrid-universal/issues/1601
=> docs: testing hints for vitest

src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts
Reverts ghiscoding/Angular-Slickgrid#1480
=> Revert "fix: redraw all open row details whenever the grid is re-rendered"

src/app/modules/angular-slickgrid/extensions/__tests__/slickRowDetailView.spec.ts, src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts
=> fix: Row Detail redraw all Views when GridMenu/ColPicker columns changes

package.json
- we should make sure user installs Angular 18.0 or higher
=> fix: add missing peer dep on Angular
